#!/usr/bin/env python3
"""bin2c.py OUT.c NAME FILE [NAME FILE ...]: binary files as C arrays (NAME[], NAME_size)."""
import sys

out = ["/* generated by scripts/bin2c.py - do not edit */\n"]
for name, path in zip(sys.argv[2::2], sys.argv[3::2]):
    data = open(path, "rb").read()
    out.append("const unsigned int %s_size = %d;\nconst unsigned char %s[] = {\n" % (name, len(data), name))
    for i in range(0, len(data), 20):
        out.append("  " + ",".join(str(b) for b in data[i:i + 20]) + ",\n")
    out.append("};\n")
open(sys.argv[1], "w").write("".join(out))
